import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, MapPin, Search, Users, X } from "lucide-react";
import { campusEvents } from "../../data/mockData";
import { PageHeader } from "../ui/PageHeader";
import { MotionBackdrop, MotionReveal } from "../ui/Motion";

const topics=["Everything","Today","Creative","Technical","Sport","Community"];
const matchesTopic=(category:string,topic:string)=>{if(topic==="Everything"||topic==="Today")return true;const value=category.toLowerCase();if(topic==="Creative")return /cultur|festival|perform|literary|art/.test(value);if(topic==="Technical")return /tech|code|build|hack/.test(value);if(topic==="Sport")return /sport|athletic/.test(value);return /freshers|campus|community/.test(value)};
export function ExploreView(){const [topic,setTopic]=useState("Everything");const [query,setQuery]=useState("");const [selected,setSelected]=useState<(typeof campusEvents)[number]|null>(null);const [planned,setPlanned]=useState<Set<string>>(()=>new Set());const items=useMemo(()=>campusEvents.filter(event=>`${event.name} ${event.category} ${event.host}`.toLowerCase().includes(query.toLowerCase())&&matchesTopic(event.category,topic)),[query,topic]);useEffect(()=>{if(!selected)return;const close=(event:KeyboardEvent)=>event.key==="Escape"&&setSelected(null);window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[selected]);return <section className="mx-auto min-h-screen w-full max-w-6xl">
  <PageHeader title="Campus pulse" eyebrow="Discover"/>
  <div className="px-4 py-8 sm:px-8"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#ed111c]">Live around TIET</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold leading-[1.02] tracking-[-.05em] sm:text-6xl">Find a reason to step outside.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-neutral-500">Events ranked by time and relevance—not likes, followers, or virality.</p></div><label className="flex h-12 min-w-72 items-center gap-3 rounded-sm border border-black/10 bg-white px-4 shadow-sm dark:border-white/10 dark:bg-white/5"><Search size={18}/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campus"/>{query?<button onClick={()=>setQuery("")}><X size={16}/></button>:null}</label></div>
    <div className="mt-9 flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{topics.map(item=><button className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold transition duration-150 active:scale-[.96] motion-reduce:transform-none motion-reduce:transition-none ${topic===item?"bg-[#ed111c] text-white shadow-[0_8px_24px_rgba(237,17,28,.18)]":"border border-black/10 bg-white text-neutral-500 hover:border-black/30 dark:border-white/10 dark:bg-white/5"}`} onClick={()=>setTopic(item)} key={item}>{item}</button>)}</div>
    {items.length?<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((event,index)=><MotionReveal key={`${topic}-${event.name}`} delay={Math.min(index*35,175)} distance={8} scale={0.99} className={index===0?"sm:col-span-2":""}><button className={`group relative min-h-72 w-full overflow-hidden rounded-md bg-black text-left text-white transition duration-200 ease-out hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(0,0,0,.18)] active:translate-y-0 active:scale-[.99] motion-reduce:transform-none motion-reduce:transition-none ${index===0?"lg:min-h-[420px]":""}`} onClick={()=>setSelected(event)}><img className="absolute inset-0 size-full object-cover opacity-70 transition duration-500 ease-out group-hover:scale-[1.035] motion-reduce:transition-none" src={event.image} alt=""/><span className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-transparent"/><span className="absolute left-4 top-4 rounded-full bg-[#ed111c] px-3 py-1.5 text-[9px] font-bold tracking-[.14em]">{planned.has(event.name)?"IN YOUR DAY":index%2?"TONIGHT":"OPEN NOW"}</span><span className="absolute inset-x-5 bottom-5"><small className="flex items-center gap-1.5 text-[10px] text-white/65"><MapPin size={12}/>TIET Patiala</small><strong className="mt-2 block text-2xl font-semibold tracking-[-.03em]">{event.name}</strong><span className="mt-2 flex items-center justify-between text-[11px] text-white/70">{event.category}<ArrowUpRight size={17}/></span></span></button></MotionReveal>)}</div>:<div className="mt-8 border-y border-black/10 py-16 text-center dark:border-white/10"><Search className="mx-auto text-neutral-300" size={34}/><h3 className="mt-3 font-semibold">Nothing matches this view</h3><p className="mt-1 text-sm text-neutral-500">Try another topic or clear your search.</p></div>}
  </div>
  {selected?<MotionBackdrop className="fixed inset-0 z-40 grid place-items-center bg-black/80 p-4 backdrop-blur-md" onMouseDown={()=>setSelected(null)}><MotionReveal className="w-full max-w-2xl overflow-hidden rounded-md bg-white text-black shadow-[0_30px_100px_rgba(0,0,0,.35)] dark:bg-[#111113] dark:text-white" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="relative h-72"><img className="size-full object-cover" src={selected.image} alt=""/><button className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-black/70 text-white transition active:scale-90 motion-reduce:transform-none motion-reduce:transition-none" onClick={()=>setSelected(null)} aria-label="Close event details"><X/></button></div><div className="p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ed111c]">{selected.category}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{selected.name}</h2><p className="mt-3 text-sm leading-6 text-neutral-500">Hosted by {selected.host}. Join people across campus for a focused, welcoming session.</p><div className="mt-6 flex flex-wrap gap-4 text-xs text-neutral-500"><span className="flex items-center gap-2"><CalendarDays size={15}/>Today, 6:00 PM</span><span className="flex items-center gap-2"><Users size={15}/>Open to everyone</span></div><button className={`mt-7 w-full rounded-sm py-3.5 text-sm font-semibold transition duration-150 active:scale-[.98] motion-reduce:transform-none motion-reduce:transition-none ${planned.has(selected.name)?"bg-neutral-100 text-neutral-700 dark:bg-white/10 dark:text-white":"bg-[#ed111c] text-white"}`} onClick={()=>setPlanned(current=>{const next=new Set(current);next.has(selected.name)?next.delete(selected.name):next.add(selected.name);return next})}>{planned.has(selected.name)?"Added to your day":"Add to my day"}</button></div></MotionReveal></MotionBackdrop>:null}
</section>}
