import { useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, MapPin, Search, Users, X } from "lucide-react";
import { campusEvents } from "../../data/mockData";
import { PageHeader } from "../ui/PageHeader";

const topics=["Everything","Today","Creative","Technical","Sport","Community"];
export function ExploreView(){const [topic,setTopic]=useState("Everything");const [query,setQuery]=useState("");const [selected,setSelected]=useState<(typeof campusEvents)[number]|null>(null);const items=useMemo(()=>campusEvents.filter(event=>`${event.name} ${event.category} ${event.host}`.toLowerCase().includes(query.toLowerCase())),[query]);return <section className="mx-auto min-h-screen w-full max-w-6xl">
  <PageHeader title="Campus pulse" eyebrow="Discover"/>
  <div className="px-4 py-8 sm:px-8"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#ed111c]">Live around TIET</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold leading-[1.02] tracking-[-.05em] sm:text-6xl">Find a reason to step outside.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-neutral-500">Events ranked by time and relevance—not likes, followers, or virality.</p></div><label className="flex h-12 min-w-72 items-center gap-3 rounded-sm border border-black/10 bg-white px-4 shadow-sm dark:border-white/10 dark:bg-white/5"><Search size={18}/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campus"/>{query?<button onClick={()=>setQuery("")}><X size={16}/></button>:null}</label></div>
    <div className="mt-9 flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{topics.map(item=><button className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold transition ${topic===item?"bg-[#ed111c] text-white":"border border-black/10 bg-white text-neutral-500 hover:border-black/30 dark:border-white/10 dark:bg-white/5"}`} onClick={()=>setTopic(item)} key={item}>{item}</button>)}</div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((event,index)=><button className={`group relative min-h-72 overflow-hidden rounded-md bg-black text-left text-white ${index===0?"sm:col-span-2 lg:min-h-[420px]":""}`} key={event.name} onClick={()=>setSelected(event)}><img className="absolute inset-0 size-full object-cover opacity-70 transition duration-500 ease-out group-hover:scale-[1.035] motion-reduce:transition-none" src={event.image} alt=""/><span className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-transparent"/><span className="absolute left-4 top-4 rounded-full bg-[#ed111c] px-3 py-1.5 text-[9px] font-bold tracking-[.14em]">{index%2?"TONIGHT":"OPEN NOW"}</span><span className="absolute inset-x-5 bottom-5"><small className="flex items-center gap-1.5 text-[10px] text-white/65"><MapPin size={12}/>TIET Patiala</small><strong className="mt-2 block text-2xl font-semibold tracking-[-.03em]">{event.name}</strong><span className="mt-2 flex items-center justify-between text-[11px] text-white/70">{event.category}<ArrowUpRight size={17}/></span></span></button>)}</div>
  </div>
  {selected?<div className="fixed inset-0 z-40 grid place-items-center bg-black/80 p-4 backdrop-blur-md" onMouseDown={()=>setSelected(null)}><article className="w-full max-w-2xl overflow-hidden rounded-md bg-white text-black shadow-lg dark:bg-[#111113] dark:text-white" onMouseDown={e=>e.stopPropagation()}><div className="relative h-72"><img className="size-full object-cover" src={selected.image} alt=""/><button className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-black/70 text-white" onClick={()=>setSelected(null)}><X/></button></div><div className="p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ed111c]">{selected.category}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{selected.name}</h2><p className="mt-3 text-sm leading-6 text-neutral-500">Hosted by {selected.host}. Join people across campus for a focused, welcoming session.</p><div className="mt-6 flex flex-wrap gap-4 text-xs text-neutral-500"><span className="flex items-center gap-2"><CalendarDays size={15}/>Today, 6:00 PM</span><span className="flex items-center gap-2"><Users size={15}/>Open to everyone</span></div><button className="mt-7 w-full rounded-sm bg-[#ed111c] py-3.5 text-sm font-semibold text-white">Add to my day</button></div></article></div>:null}
</section>}
