import { useState } from "react";
import { Archive, Bookmark, Grid3X3, Plus, Settings, Users } from "lucide-react";
import { exploreItems } from "../../data/mockData";
import type { Post, Story, UserProfile } from "../../types/social";
import { PageHeader } from "../ui/PageHeader";
import { MotionReveal } from "../ui/Motion";
type Props={user:UserProfile;posts:Post[];savedIds:Set<number>;onSettings:()=>void;onPreview:(label:string)=>void;onFollowers:()=>void;onFollowing:()=>void;onManageStories:()=>void;highlights:Story[]};
type Tab="updates"|"saved"|"collabs";
export function ProfileView({user,posts,savedIds,onSettings,onPreview,onFollowers,onFollowing,onManageStories,highlights}:Props){const [tab,setTab]=useState<Tab>("updates");const own=posts.filter(p=>p.handle===user.username);const saved=posts.filter(p=>savedIds.has(p.id));const images=tab==="updates"?(own.length?own.map(p=>p.image):["/images/library.webp","/images/friends.webp","/images/campus.webp"]):tab==="saved"?saved.map(p=>p.image):exploreItems.slice(3,9).map(i=>i.image);return <section className="mx-auto min-h-screen w-full max-w-5xl"><PageHeader title="Your profile" eyebrow={`@${user.username}`} action={<button className="grid size-10 place-items-center rounded-full border border-black/10 dark:border-white/10" onClick={onSettings}><Settings size={18}/></button>}/><div className="px-4 py-8 sm:px-8">
  <div className="grid gap-8 rounded-md bg-black p-6 text-white shadow-lg sm:grid-cols-[140px_1fr] sm:p-9"><img className="size-28 rounded-md object-cover ring-1 ring-white/20 sm:size-36" src={user.avatar} alt={user.name}/><div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ed111c]">Verified TIET member</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.045em]">{user.name}</h1><p className="mt-2 text-sm text-white/55">{user.branch} · {user.year}</p></div><button className="rounded-sm bg-white px-4 py-2.5 text-xs font-semibold text-black" onClick={onSettings}>Edit profile</button></div><p className="mt-6 max-w-xl text-sm leading-6 text-white/70">{user.bio}</p><div className="mt-7 flex flex-wrap gap-6 text-sm"><span><b className="block text-xl">{images.length}</b><small className="text-white/45">contributions</small></span><button onClick={onFollowers}><b className="block text-xl">{user.followers.toLocaleString()}</b><small className="text-white/45">connections</small></button><button onClick={onFollowing}><b className="block text-xl">{user.following.toLocaleString()}</b><small className="text-white/45">people known</small></button></div></div></div>
  <div className="mt-10 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ed111c]">Your circles</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Spaces you keep close</h2></div><button className="flex items-center gap-2 text-xs font-semibold text-neutral-500" onClick={onManageStories}><Plus size={15}/>New space</button></div><div className="mt-5 flex gap-3 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button className="grid min-h-28 min-w-40 content-between rounded-sm border border-dashed border-black/20 p-4 text-left dark:border-white/20" onClick={onManageStories}><Plus size={18}/><span><b className="block text-sm">Start a circle</b><small className="text-[9px] text-neutral-500">Invite collaborators</small></span></button>{highlights.map((item,index)=><button className="relative min-h-28 min-w-44 overflow-hidden rounded-sm text-left text-white" key={`${item.image}-${index}`} onClick={onManageStories}><img className="absolute inset-0 size-full object-cover" src={item.image} alt=""/><span className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><b className="absolute bottom-3 left-3">Circle {index+1}</b></button>)}</div>
  <div className="mt-10 flex gap-2 border-b border-black/10 dark:border-white/10">{([{id:"updates",label:"Contributions",icon:Grid3X3},{id:"saved",label:"Saved",icon:Bookmark},{id:"collabs",label:"Collaborations",icon:Users}] as const).map(({id,label,icon:Icon})=><button className={`flex items-center gap-2 border-b-2 px-3 py-3 text-xs font-semibold transition duration-150 active:scale-[.97] motion-reduce:transform-none motion-reduce:transition-none ${tab===id?"border-[#ed111c] text-[#ed111c]":"border-transparent text-neutral-500 hover:text-[#171719] dark:hover:text-white"}`} onClick={()=>setTab(id)} key={id}><Icon className={`transition-transform duration-150 motion-reduce:transition-none ${tab===id?"scale-110":""}`} size={15}/>{label}</button>)}</div>
  {images.length?<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{images.map((image,index)=><MotionReveal key={`${tab}-${image}-${index}`} delay={Math.min(index*35,175)} distance={7} scale={0.99}><button className="group relative aspect-[4/3] w-full overflow-hidden rounded-sm bg-neutral-100 transition duration-150 hover:-translate-y-0.5 hover:shadow-lg active:translate-y-0 active:scale-[.99] motion-reduce:transform-none motion-reduce:transition-none" onClick={()=>onPreview("Contribution opened")}><img className="size-full object-cover transition duration-500 group-hover:scale-[1.03] motion-reduce:transition-none" src={image} alt=""/><span className="absolute inset-0 flex items-end bg-gradient-to-t from-black/70 to-transparent p-4 text-left text-sm font-semibold text-white opacity-0 transition duration-200 group-hover:opacity-100 motion-reduce:transition-none">Open contribution</span></button></MotionReveal>)}</div>:<MotionReveal key={tab} className="py-20 text-center" distance={6} scale={1}><Archive className="mx-auto text-neutral-300" size={38}/><h2 className="mt-4 text-xl font-semibold">Nothing saved yet</h2><p className="mt-2 text-sm text-neutral-500">Useful campus updates you save will appear here.</p></MotionReveal>}
</div></section>}
