import { ChangeEvent, useEffect, useState } from "react";
import { CalendarDays, ImagePlus, MapPin, Sparkles, Users, X } from "lucide-react";
import type { ContentKind, NewContentInput } from "../../types/social";

type Props={initialKind?:ContentKind;onClose:()=>void;onShare:(content:NewContentInput)=>void};
const kinds:{id:ContentKind;label:string}[]=[{id:"post",label:"Update"},{id:"story",label:"Invite"},{id:"reel",label:"Clip"}];

export function ComposerModal({initialKind="post",onClose,onShare}:Props){
  const [kind,setKind]=useState<ContentKind>(initialKind); const [caption,setCaption]=useState(""); const [media,setMedia]=useState(""); const [mediaType,setMediaType]=useState<"image"|"video">("image");
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);
  const readMedia=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setMediaType(file.type.startsWith("video/")?"video":"image");const reader=new FileReader();reader.onload=()=>setMedia(String(reader.result));reader.readAsDataURL(file)};
  const useDemo=()=>{if(kind==="reel"){setMedia("/videos/campus-reel.mp4");setMediaType("video")}else{setMedia(kind==="story"?"/images/campus.webp":"/images/library.webp");setMediaType("image")}};
  const publish=()=>media&&onShare({kind,image:media,mediaType,caption:caption.trim()||(kind==="story"?"Meet us on campus.":"A useful update from campus.")});
  return <div className="fixed inset-0 z-40 grid place-items-center bg-black/75 p-4 backdrop-blur-md" role="presentation" onMouseDown={onClose}><section className="w-full max-w-[620px] overflow-hidden rounded-md bg-white text-[#171719] shadow-[0_30px_100px_rgba(0,0,0,.35)] dark:bg-[#111113] dark:text-white" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}>
    <header className="flex min-h-20 items-center justify-between border-b border-black/10 px-6 dark:border-white/10"><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-[#ed111c]">Add to campus</p><h2 className="mt-1 text-xl font-semibold tracking-[-.025em]">What are you making happen?</h2></div><button className="grid size-10 place-items-center rounded-full border border-black/10 hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/5" onClick={onClose}><X size={19}/></button></header>
    <div className="flex gap-2 px-6 pt-5">{kinds.map(item=><button className={`rounded-full border px-4 py-2 text-xs font-semibold transition motion-reduce:transition-none ${kind===item.id?"border-[#ed111c] bg-[#ed111c] text-white":"border-black/10 text-neutral-500 hover:border-black/30 dark:border-white/10"}`} onClick={()=>{setKind(item.id);setMedia("")}} key={item.id}>{item.label}</button>)}</div>
    {media?<div className={`relative mx-6 mt-5 overflow-hidden rounded-sm bg-black ${kind==="story"||kind==="reel"?"mx-auto aspect-[9/16] max-h-[360px] w-[220px]":"aspect-[16/9] max-h-[310px]"}`}>{mediaType==="video"?<video className="size-full object-cover" src={media} controls autoPlay muted loop/>:<img className="size-full object-cover" src={media} alt="Preview"/>}<button className="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-black/70 text-white" onClick={()=>setMedia("")}><X size={16}/></button></div>:<div className="mx-6 mt-5 flex h-[230px] flex-col items-center justify-center gap-3 rounded-sm border border-dashed border-black/20 bg-[#f8f8f6] dark:border-white/20 dark:bg-white/[.03]"><span className="grid size-14 place-items-center rounded-md bg-black text-white dark:bg-white dark:text-black"><ImagePlus size={25}/></span><strong className="font-medium">Add a photo or video</strong><label className="cursor-pointer rounded-sm bg-[#ed111c] px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-red-600/15">Choose from device<input className="sr-only" type="file" accept={kind==="reel"?"image/*,video/*":"image/*"} onChange={readMedia}/></label><button className="text-xs font-semibold text-neutral-500 hover:text-[#ed111c]" onClick={useDemo}>Use demo media</button></div>}
    <textarea className="mx-6 mt-5 min-h-24 w-[calc(100%_-_3rem)] resize-y border-y border-black/10 bg-transparent py-4 font-serif text-xl outline-none placeholder:text-neutral-400 dark:border-white/10" value={caption} onChange={event=>setCaption(event.target.value)} maxLength={1200} placeholder={kind==="story"?"What should people know before joining?":"Share something useful with campus…"}/>
    <div className="mx-6 mt-4 flex gap-2 overflow-x-auto pb-1"><button className="flex shrink-0 items-center gap-2 rounded-sm border border-black/10 px-3 py-2 text-[10px] text-neutral-500 dark:border-white/10"><CalendarDays size={14}/>When</button><button className="flex shrink-0 items-center gap-2 rounded-sm border border-black/10 px-3 py-2 text-[10px] text-neutral-500 dark:border-white/10"><MapPin size={14}/>Where</button><button className="flex shrink-0 items-center gap-2 rounded-sm border border-black/10 px-3 py-2 text-[10px] text-neutral-500 dark:border-white/10"><Users size={14}/>Audience</button></div>
    <div className="flex items-center justify-between px-6 py-5"><span className="text-[10px] text-neutral-500">{caption.length}/1,200</span><button className="flex items-center gap-2 rounded-sm bg-[#ed111c] px-5 py-2.5 text-xs font-semibold text-white shadow-lg shadow-red-600/15 disabled:opacity-40" disabled={!media} onClick={publish}><Sparkles size={15}/>Publish</button></div>
  </section></div>;
}
