import { ChangeEvent, useEffect, useState } from 'react'
import { Clapperboard, ImagePlus, PlusCircle, X } from 'lucide-react'
import type { ContentKind, NewContentInput } from '../../types/social'

type ComposerModalProps = { initialKind?: ContentKind; onClose: () => void; onShare: (content: NewContentInput) => void }

const kinds: { id: ContentKind; label: string }[] = [{ id: 'post', label: 'Post' }, { id: 'story', label: 'Story' }, { id: 'reel', label: 'Reel' }]

export function ComposerModal({ initialKind = 'post', onClose, onShare }: ComposerModalProps) {
  const [kind, setKind] = useState<ContentKind>(initialKind)
  const [caption, setCaption] = useState('')
  const [media, setMedia] = useState('')
  const [mediaType, setMediaType] = useState<'image' | 'video'>('image')

  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape) }, [onClose])
  const readMedia = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setMediaType(file.type.startsWith('video/') ? 'video' : 'image'); const reader = new FileReader(); reader.onload = () => setMedia(String(reader.result)); reader.readAsDataURL(file) }
  const useDemo = () => { if (kind === 'reel') { setMedia('/videos/campus-reel.mp4'); setMediaType('video') } else { setMedia(kind === 'story' ? '/images/campus.jpg' : '/images/library.jpg'); setMediaType('image') } }
  const share = () => media && onShare({ kind, image: media, mediaType, caption: caption.trim() || (kind === 'story' ? 'A campus moment ✨' : 'A new moment from campus.') })

  return <div className="fixed inset-0 z-30 grid place-items-center bg-black/65 p-4" role="presentation" onMouseDown={onClose}><section className="w-full max-w-[590px] overflow-hidden rounded-xl bg-white shadow-2xl" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><header className="relative flex min-h-12 items-center justify-center border-b border-neutral-200"><h2 className="text-base font-semibold">Create new {kind}</h2><button className="absolute right-2 grid size-9 place-items-center rounded-lg hover:bg-neutral-100" onClick={onClose}><X /></button></header><div className="flex border-b border-neutral-200">{kinds.map((item) => <button className={`flex-1 py-3 text-sm font-semibold ${kind === item.id ? 'border-b-2 border-black' : 'text-neutral-400'}`} onClick={() => { setKind(item.id); setMedia('') }} key={item.id}>{item.label}</button>)}</div>{media ? <div className={`relative m-4 overflow-hidden rounded-lg bg-neutral-950 ${kind === 'story' || kind === 'reel' ? 'mx-auto aspect-[9/16] max-h-[390px] w-[220px]' : 'aspect-square max-h-[340px]'}`}>{mediaType === 'video' ? <video className="size-full object-cover" src={media} controls autoPlay muted loop /> : <img className="size-full object-cover" src={media} alt="Content preview" />}<button className="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-black/65 text-white" onClick={() => setMedia('')}><X size={17} /></button></div> : <div className="m-4 flex h-[260px] flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-neutral-400 bg-neutral-50">{kind === 'reel' ? <Clapperboard size={48} strokeWidth={1.4} /> : kind === 'story' ? <PlusCircle size={48} strokeWidth={1.4} /> : <ImagePlus size={48} strokeWidth={1.4} />}<strong className="font-normal">Choose {kind === 'reel' ? 'a video or cover' : 'a photo'} to share</strong><label className="cursor-pointer rounded-lg bg-blue-500 px-4 py-2 text-sm font-semibold text-white">Select from device<input className="sr-only" type="file" accept={kind === 'reel' ? 'image/*,video/*' : 'image/*'} onChange={readMedia} /></label><button className="text-xs font-semibold text-blue-500" onClick={useDemo}>Use demo {kind}</button></div>}<textarea className="mx-4 min-h-20 w-[calc(100%_-_2rem)] resize-y rounded-lg border border-neutral-200 p-3 outline-none focus:border-neutral-400" value={caption} onChange={(event) => setCaption(event.target.value)} maxLength={2200} placeholder={kind === 'story' ? 'Add story text…' : 'Write a caption…'} /><div className="flex items-center justify-between px-4 py-3.5"><span className="text-xs text-neutral-500">{caption.length}/2,200</span><button className="font-semibold text-blue-500 disabled:opacity-40" disabled={!media} onClick={share}>Share</button></div></section></div>
}
