import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Plus } from "lucide-react";
import type { UserProfile } from "../../types/social";
import { MotionReveal } from "../ui/Motion";

type Props={following:Set<string>;user:UserProfile;expanded:boolean;onToggle:()=>void;onFollow:(handle:string)=>void;onPreview:(label:string)=>void};
const agenda=[{time:"10:30",title:"Design critique",meta:"LT 104 · 7 classmates",color:"bg-[#ed111c]"},{time:"14:00",title:"FAPS photo walk",meta:"Library lawns · Open invite",color:"bg-[#ed111c]"},{time:"18:30",title:"CCS build night",meta:"TAN 201 · Bring your laptop",color:"bg-[#6f91a8]"}];

export function RightRail({following,expanded,onToggle,onFollow,onPreview}:Props){
  const joined=following.has("@faps.tiet");
  return <aside className={`relative hidden min-w-0 border-l border-[#171719]/10 dark:border-white/10 xl:block ${expanded?"pl-8 pt-[58px]":"pt-6"}`}>
    <button className={`grid size-9 place-items-center rounded-full border border-black/10 bg-white text-neutral-500 shadow-sm transition duration-150 hover:border-[#ed111c]/40 hover:text-[#ed111c] active:scale-90 dark:border-white/10 dark:bg-white/5 motion-reduce:transform-none motion-reduce:transition-none ${expanded?"absolute right-0 top-5":"mx-auto"}`} onClick={onToggle} aria-label={expanded?"Collapse right panel":"Expand right panel"} title={expanded?"Collapse panel":"Expand panel"}>{expanded?<ChevronRight size={17}/>:<ChevronLeft size={17}/>}</button>
    {expanded?<MotionReveal distance={0} scale={0.99}>
      <div className="flex items-center justify-between pr-12"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-neutral-500">Your day</p><h2 className="font-serif text-2xl font-normal">Three things ahead</h2></div><CalendarDays size={18} className="text-neutral-500"/></div>
      <div className="relative mt-7 before:absolute before:bottom-8 before:left-[50px] before:top-5 before:w-px before:bg-black/10 dark:before:bg-white/10">{agenda.map((item,index)=><button className="group relative grid min-h-[82px] w-full grid-cols-[38px_10px_1fr] gap-3 bg-transparent py-3 text-left transition duration-150 hover:translate-x-1 active:translate-x-0 motion-reduce:transform-none motion-reduce:transition-none" key={item.time} onClick={()=>onPreview(item.title)}><time className="pt-0.5 text-[10px] text-neutral-500">{item.time}</time><i className={`z-10 mt-1 size-2 rounded-full ring-4 ring-[#f7f7f5] transition-transform duration-150 group-hover:scale-125 dark:ring-[#050505] motion-reduce:transition-none ${item.color}`}/><span><strong className="block font-serif text-[15px] font-medium">{item.title}</strong><small className="mt-1.5 block text-[9px] leading-4 text-neutral-500">{item.meta}</small>{index===0?<b className="mt-2 block text-[8px] tracking-[.14em] text-[#ed111c]">NEXT</b>:null}</span></button>)}</div>
      <button className="mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-md border border-black/10 text-[10px] text-neutral-500 transition duration-150 hover:border-black/25 active:scale-[.98] dark:border-white/10 dark:hover:border-white/25 motion-reduce:transform-none motion-reduce:transition-none" onClick={()=>onPreview("Timetable")}><Plus size={15}/>Add from timetable</button>
      <section className="mt-12 border-t border-black/10 pt-7 dark:border-white/10"><p className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-neutral-500">Picked for you</p><div className="group mt-4 overflow-hidden"><img className="h-36 w-full object-cover saturate-75 transition duration-500 ease-out group-hover:scale-[1.025] motion-reduce:transition-none" src="/images/campus.webp" alt="Campus photo walk"/></div><h3 className="mt-4 font-serif text-xl font-normal leading-tight">Golden-hour photo walk</h3><p className="mt-2 text-[10px] leading-5 text-neutral-500">No camera needed. Meet at the library lawns in 52 minutes.</p><button className={`mt-4 flex h-10 w-full items-center justify-center gap-2 rounded-md text-[11px] font-semibold transition duration-150 active:scale-[.98] motion-reduce:transform-none motion-reduce:transition-none ${joined?"bg-[#ed111c] text-white":"bg-[#171719] text-white dark:bg-white dark:text-[#171719]"}`} onClick={()=>onFollow("@faps.tiet")}>{joined?<Check size={15}/>:<Clock3 size={15}/>} {joined?"You’re going":"Join the walk"}</button></section>
    </MotionReveal>:null}
  </aside>;
}
